# Use Node.js official image
FROM node:18

# Set working directory
WORKDIR /usr/src/app

# Copy everything from current directory to working directory
COPY . .

# Navigate to the notifier app within the monorepo
WORKDIR /usr/src/app/apps/hose

RUN npm install bun -g

# Install any needed packages specified in package.json
RUN bun install

# Build the app
RUN bun run build

# Start the applications with PM2
# CMD ["pm2-runtime", "pm2.config.js"]